name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7
      - run: nix-shell --run 'go build'
      - run: ./terraform-provider-mailjet --help
  static_analysis:
    runs-on: ubuntu-22.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7
      - run: nix-shell --run 'golangci-lint run --timeout=5m'
  generate:
    runs-on: ubuntu-22.04
    name: Check generated documentation
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7
      - run: nix-shell --run 'go generate ./...'
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
