name: CI

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-22.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7
      - run: nix-shell --run 'golangci-lint run --timeout=5m'
  test_release:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    name: Test release
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7
      - run: nix-shell --run 'goreleaser --snapshot --clean'
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: test-release-dist
          path: dist/**/*
          retention-days: 2
